# Generated by Django 3.2.9 on 2021-11-18 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactsmodel',
            old_name='phno',
            new_name='phone_no',
        ),
    ]
